### ISSUE TITLE
KeyError: 'valid'

### ISSUE THREAD

**Issue by iwtga** [TermuxHackz/X-osint#10]
The script crashes when trying to find email information (option 2):

```shell
Traceback (most recent call last):                                                                                                                           
  File "/usr/local/bin/xosint", line 480, in <module>                                                                                                        
    email_info()                                                                                                                                             
  File "/usr/local/bin/xosint", line 200, in email_info                                                                                                      
    print("\033[1;91m➤\033[1;97m Valid               : " + str(eml.json() ['valid']))                                                                        
                                                               ~~~~~~~~~~^^^^^^^^^^                                                                          
KeyError: 'valid' 
```

**Comment by TermuxHackz** [comment]
Thanks for letting me know about this issue, I would do my best to resolve it and let you know on future updates you would need to make after I have fixed the bug. Once again thanks @iwtga

**Comment by kuklofon** [comment]
![изображение](https://github.com/TermuxHackz/X-osint/assets/20505953/638ea624-36e3-4fd4-ad6c-68cab332a461)
Kali Linux
