### ISSUE TITLE
X-osint error in termux

### ISSUE THREAD

**Issue by Travelling-Human** [TermuxHackz/X-osint#49]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 21, in <module>
    from prompt_toolkit import print_formatted_text, HTML
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/data/data/com.termux/files/usr/lib/python3.11/collections/__init__.py)

This is what I got when I tried to run x-osint in termux. What is the problem here?

**Comment by Travelling-Human** [comment]
Thank you for the response
