### ISSUE TITLE
termux

### ISSUE THREAD

**Issue by aeleaeth** [TermuxHackz/X-osint#52]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 29, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by TermuxHackz** [comment]
@aeleaeth Kindly type pkg install tk

**Comment by aeleaeth** [comment]
@TermuxHackz Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 29, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by TermuxHackz** [comment]
@aeleaeth , I have made a minor change to X-osint so you should no longer run into those errors again
Thank you

**Comment by aeleaeth** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 33, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

I reinstall xosint , i had install tk

**Comment by TermuxHackz** [comment]
@aeleaeth install x-osint manually

**Comment by TermuxHackz** [comment]
@aeleaeth and do not skip the setup.sh process 
Reason you are most likely getting this error is due to the fact that termux doesn't have a GUI therefore tkinter wouldn't be able to install 
Although you can try to install via proot in Termux 
Type 
```
pkg install proot-distro
```

proot-distro install ubuntu
proot-distro login ubuntu

apt update
apt install python3-tk

**Comment by aeleaeth** [comment]
root@localhost:~# xosint
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 5, in <module>
    from googlesearch import search # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'googlesearch'

i installed on proot ubuntu

**Comment by TermuxHackz** [comment]
hello @aeleaeth , use the command
```
pip install google --break-system-packages
```
then
```
pip install googlesearch-python
```
to install google search

**Comment by kiradz** [comment]
spaCy not found. Installing...
taking a long time and no install, how to fix?

**Comment by TermuxHackz** [comment]
@kiradz Be sure you've got a proper stable internet connection to install it, it should be done in no time

**Comment by TermuxHackz** [comment]
Fixed. tkinter is an OS package, not a pip package — setup.sh now installs it for you via `pkg install python-tkinter` (Termux) / `apt-get install python3-tk` (Linux) as part of the normal install. Pull the latest master and re-run `bash setup.sh`.
