### ISSUE TITLE
Termux issue still her 

### ISSUE THREAD

**Issue by Travelling-Human** [TermuxHackz/X-osint#57]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 33, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

This problem is still happening in my termux

**Comment by TermuxHackz** [comment]
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/usr/bin/xosint", line 33, in <module>
>     import tkinter as tk
> ModuleNotFoundError: No module named 'tkinter'
> 
> This problem is still happening in my termux

Read [here](https://github.com/TermuxHackz/X-osint/issues/52#issuecomment-2294994598)

**Comment by Travelling-Human** [comment]
Thank your response

And I regret to inform you that this is still here:
root@localhost:~# xosint
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 5, in <module>
    from googlesearch import search # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'googlesearch'

I installed on termux

**Comment by TermuxHackz** [comment]
> Thank your response
> 
> And I regret to inform you that this is still here:
> root@localhost:~# xosint
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/usr/bin/xosint", line 5, in <module>
>     from googlesearch import search # type: ignore
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ModuleNotFoundError: No module named 'googlesearch'
> 
> I installed on termux

python3 -m pip uninstall googlesearch-python -y
python3 -m pip uninstall google-search -y
python3 -m pip uninstall google -y

Then pip install googlesearch-python

**Comment by Travelling-Human** [comment]
I am sorry but the problem is still there
I will send you the screenshots![Screenshot_2024-08-19-13-11-19-962_com.termux.jpg](https://github.com/user-attachments/assets/21b6be8f-a453-4316-a0fa-9ade48e901ba)

![Screenshot_2024-08-19-13-11-44-725_com.termux.jpg](https://github.com/user-attachments/assets/ae64d045-c01d-4b3d-a07c-4cd347e36e1e)

**Comment by TermuxHackz** [comment]
> I am sorry but the problem is still there
> I will send you the screenshots![Screenshot_2024-08-19-13-11-19-962_com.termux.jpg](https://github.com/user-attachments/assets/21b6be8f-a453-4316-a0fa-9ade48e901ba)
> 
> ![Screenshot_2024-08-19-13-11-44-725_com.termux.jpg](https://github.com/user-attachments/assets/ae64d045-c01d-4b3d-a07c-4cd347e36e1e)
> 
> 

Try these 

pip install google --break-system-packages

Then 

python3 -m pip install googlesearch-python

**Comment by Travelling-Human** [comment]
I guess we can say it kind of worked 'cause this is what it shows:

root@localhost:~# xosint
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'


What should I do

**Comment by TermuxHackz** [comment]
> I guess we can say it kind of worked 'cause this is what it shows:
> 
> root@localhost:~# xosint
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/usr/bin/xosint", line 13, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
> 
> 
> What should I do

Run pip install requests 


Every module it says not found 
Just run 
pip install <followed by the module>

**Comment by Travelling-Human** [comment]
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.




This is the response I got I tried some methods it showed but no changes seen

**Comment by TermuxHackz** [comment]
@Travelling-Human 
Add the --break-system-packages

For every module your trying to install 

Eg
pip install request --break-system-packages

**Comment by TermuxHackz** [comment]
@Travelling-Human 
Add the --break-system-packages

For every module your trying to install 

Eg
pip install request --break-system-packages

**Comment by Travelling-Human** [comment]
ERROR: Could not find a version that satisfies the requirement request (from versions: none)
ERROR: No matching distribution found for request



This the response from it

**Comment by TermuxHackz** [comment]
@Travelling-Human, add requests to it, not request

**Comment by Travelling-Human** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 14, in <module>
    from ping3 import ping
ModuleNotFoundError: No module named 'ping3' 


Just for the record I tried reinstalling and the ping and ping3 are there. I don't know what happened here

**Comment by TermuxHackz** [comment]
@Travelling-Human pip install ping3 --break-system-packages

**Comment by TermuxHackz** [comment]
there is no python module called that, it is
```
pip install  google-api-python-client
```
@Travelling-Human

**Comment by Travelling-Human** [comment]
Thank you for the response earlier. And everything. I know that I was kind of stupid not doing the research. Sorry.


Again can you help me with this too. I will try to make as few responses as possible

root@localhost:~# xosint                                   An unexpected error occurred: module 'platform' has no attribute 'linux_distribution'

**Comment by TermuxHackz** [comment]
Kindly send a screenshot

**Comment by Travelling-Human** [comment]
Ok
![Screenshot_2024-08-19-16-56-46-012_com.termux.jpg](https://github.com/user-attachments/assets/b85366eb-4ddf-480b-a6e9-77b831a31c95)

**Comment by TermuxHackz** [comment]
Oh I see, I'd need to update the code on my end so it works for your version of termux

**Comment by Travelling-Human** [comment]
Thank you so so much buddy 
Thank you 
It means so much

**Comment by TermuxHackz** [comment]
Fixed. tkinter is an OS package, not something pip can install, which is why reinstalling via pip never worked for anyone in this thread. setup.sh now installs it directly via `pkg install python-tkinter` (Termux) / `apt-get install python3-tk` (Linux) as part of the normal install, so it's there before xosint ever tries to import it. Pull the latest master and re-run `bash setup.sh`. Sorry this took so long to get fixed properly — thanks for all the details in this thread, they helped track down the real cause.

**Comment by cookie-chocolate** [comment]
i have this problem 

Traceback (most recent call last):

File "/data/data/com.termux/files/usr/bin/xosint",

ine 14, in <module> from ping3 import ping

ModuleNotFoundError: No module named 'ping3'
