### ISSUE TITLE
Always dealing with tkinter

### ISSUE THREAD

**Issue by aethereal123** [TermuxHackz/X-osint#60]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 33, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

Any just one helpful solution of this thing?

**Comment by TermuxHackz** [comment]
> Traceback (most recent call last):
> 
>   File "/data/data/com.termux/files/usr/bin/xosint", line 33, in <module>
> 
>     import tkinter as tk
> 
> ModuleNotFoundError: No module named 'tkinter'
> 
> 
> 
> Any just one helpful solution of this thing?

Hey there @aethereal123 , create a Python virtual environment and install tkinter, basically install all the Python packages in a Python virtual environment and then start Xosint , everything should work well 
Visit the README for Xosint on how to create a Python virtual environment

**Comment by aethereal123** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 22, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
(venv) ➜  ~ pip install PIL --break-system-packages
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL


What should i do for PIL? pip doesnt work any solutions?

**Comment by TermuxHackz** [comment]
> Traceback (most recent call last): File "/data/data/com.termux/files/usr/bin/xosint", line 22, in from PIL import Image ModuleNotFoundError: No module named 'PIL' (venv) ➜ ~ pip install PIL --break-system-packages ERROR: Could not find a version that satisfies the requirement PIL (from versions: none) ERROR: No matching distribution found for PIL
> 
> What should i do for PIL? pip doesnt work any solutions?

Hi there @aethereal123 install pillow 

pip install pillow

**Comment by aethereal123** [comment]
Nuh uh its still dealing with tkinter / tk, after running python enviroment its still same
![Uploading Screenshot_2024-10-01-17-51-37-962_com.termux.jpg…]()

**Comment by TermuxHackz** [comment]
@aethereal123  Now that you have created a python virtual environment you would need to reinstall the python packages the bot needs. 
eg
- pip install tk

and so on...

**Comment by aethereal123** [comment]
Nah dude tk is always catching me up 😭
![Screenshot_2024-10-04-16-33-38-886_com termux](https://github.com/user-attachments/assets/51e2d5f4-2099-4c80-ab7c-2cb26e7ed014)

please help me

**Comment by aethereal123** [comment]
![Screenshot_2024-10-04-16-39-47-786_com termux](https://github.com/user-attachments/assets/ceb83fe6-e40e-424e-b3bc-385faa281783)

any slight better solutions?

**Comment by TermuxHackz** [comment]
Hi @aethereal123 Try the following 
- pip install tk-tools

**Comment by aethereal123** [comment]
![Screenshot_2024-10-04-16-41-47-173_com termux](https://github.com/user-attachments/assets/75e535d1-6cd3-4c2a-929c-a5b65310925a)

Same thing happened

**Comment by TermuxHackz** [comment]
HI @aethereal123 Your likely experiencing this because tkinker isnt really available for Termux, but you'll need to use an X11 server and install the X11 packages.
Install the Following:
- pkg update
- pkg install x11-repo
- pkg install python python-tkinter

Then Install an X11 server app on your Android device. VNC Viewer is a popular choice.
Install a VNC server in Termux:
- pkg install tigervnc

Start the VNC Server
- vncserver

Set a password when prompted.
Connect to the VNC server using the VNC Viewer app on your Android device.
Now you should be able to run it properly

**Comment by aethereal123** [comment]
How to use the vnc server?

**Comment by aethereal123** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 48, in <module>
    from cryptography.fernet import Fernet # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'cryptography'
(X-osint_venv) ➜  X-osint pip install cryptography
The folder you are executing pip from can no longer be found.
(X-osint_venv) ➜  X-osint pkg install cryptography
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://mirrors.nguyenhoang.cloud/termux/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cryptography

What is cryptography and how to install it?

**Comment by TermuxHackz** [comment]
Hi @aethereal123 I would suggest you delete X-osint from your termux and re-install as ive added a new requirements.txt file which contains all the necessary pip packages to install for X-osint
OR you can download it here 
[requirements.txt](https://github.com/user-attachments/files/17256557/requirements.txt)
Access your downloads folder on your phone in termux, then move it to the home folder of termux and then run pip install -r requirements.txt and then you can proceed with the installation of X-osint

**Comment by TermuxHackz** [comment]
In Addition @aethereal123 You can view the requirements.txt file, and see which packages you need to install and then install it using pip install <packagename> 
eg pip install cryptography==3.4.8
ETC

**Comment by aethereal123** [comment]
How to uninstall it?

**Comment by TermuxHackz** [comment]
sighs, you dont need to @aethereal123 , just do this instead https://github.com/TermuxHackz/X-osint/issues/60#issuecomment-2393337457

**Comment by TermuxHackz** [comment]
view the requirements.txt file, and see which packages you need to install and then install it using pip install package_name
eg pip install cryptography==3.4.8
ETC

**Comment by aethereal123** [comment]
X-osint git:(master) ✗ pip install cryptography==3.4.8
Collecting cryptography==3.4.8
  Using cached cryptography-3.4.8.tar.gz (546 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi>=1.12 (from cryptography==3.4.8)
  Using cached cffi-1.17.1-cp311-cp311-linux_aarch64.whl
Collecting pycparser (from cffi>=1.12->cryptography==3.4.8)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [341 lines of output]
33 warnings and 6 errors generated.

          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation.html for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq.html
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation.html#rust
          5) If you are experiencing issues with Rust for *this release only* you may
             set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
          =============================DEBUG ASSISTANCE=============================

      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cryptography

As the results
Any solutions?

**Comment by raayraay96** [comment]
Hey im having same issue its for the gui right? Any solution or just running no gui?

**Comment by raayraay96** [comment]
i got it to run on userland finally

**Comment by hussein00910** [comment]
pip install googlesearch-python
