### ISSUE TITLE
DEV, HELP MEE

### ISSUE THREAD

**Issue by 6oname** [TermuxHackz/X-osint#63]
I can't install spaCy

**Comment by 6oname** [comment]
![Uploading Screenshot_20241021_084710_Termux.jpg…]()

**Comment by 6oname** [comment]
└─[~]────►pip install spacy
Collecting spacy
  Using cached spacy-3.8.2.tar.gz (1.3 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [182 lines of output]
      Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
      Collecting setuptools
        Using cached setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
      Collecting cython<3.0,>=0.25
        Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Using cached cymem-2.0.8-cp312-cp312-linux_aarch64.whl
      Collecting preshed<3.1.0,>=3.0.2
        Using cached preshed-3.0.9.tar.gz (14 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting murmurhash<1.1.0,>=0.28.0
        Using cached murmurhash-1.0.10-cp312-cp312-linux_aarch64.whl
      Collecting thinc<8.4.0,>=8.3.0
        Using cached thinc-8.3.2.tar.gz (193 kB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 1
        ╰─> [145 lines of output]
            Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
            Collecting setuptools
              Using cached setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
            Collecting cython<3.0,>=0.25
              Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
            Collecting murmurhash<1.1.0,>=1.0.2
              Using cached murmurhash-1.0.10-cp312-cp312-linux_aarch64.whl
            Collecting cymem<2.1.0,>=2.0.2
              Using cached cymem-2.0.8-cp312-cp312-linux_aarch64.whl
            Collecting preshed<3.1.0,>=3.0.2
              Using cached preshed-3.0.9.tar.gz (14 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting blis<1.1.0,>=1.0.0
              Using cached blis-1.0.1.tar.gz (3.6 MB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'error'
              error: subprocess-exited-with-error

              × pip subprocess to install build dependencies did not run successfully.
              │ exit code: 1
              ╰─> [109 lines of output]
                  Collecting setuptools
                    Using cached setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
                  Collecting cython>=0.25
                    Using cached Cython-3.0.11-py2.py3-none-any.whl.metadata (3.2 kB)
                  Collecting numpy<3.0.0,>=2.0.0
                    Using cached numpy-2.1.2.tar.gz (18.9 MB)
                    Installing build dependencies: started
                    Installing build dependencies: finished with status 'done'
                    Getting requirements to build wheel: started
                    Getting requirements to build wheel: finished with status 'done'
                    Installing backend dependencies: started
                    Installing backend dependencies: finished with status 'error'
                    error: subprocess-exited-with-error

                    × pip subprocess to install backend dependencies did not run successfully.
                    │ exit code: 1
                    ╰─> [82 lines of output]
                        Collecting ninja>=1.8.2
                          Using cached ninja-1.11.1.1.tar.gz (132 kB)
                          Installing build dependencies: started
                          Installing build dependencies: finished with status 'done'
                          Getting requirements to build wheel: started
                          Getting requirements to build wheel: finished with status 'done'
                          Preparing metadata (pyproject.toml): started
                          Preparing metadata (pyproject.toml): finished with status 'done'
                        Collecting patchelf>=0.11.0
                          Using cached patchelf-0.17.2.1.tar.gz (167 kB)
                          Installing build dependencies: started
                          Installing build dependencies: finished with status 'done'
                          Getting requirements to build wheel: started
                          Getting requirements to build wheel: finished with status 'done'
                          Preparing metadata (pyproject.toml): started
                          Preparing metadata (pyproject.toml): finished with status 'done'
                        Building wheels for collected packages: ninja, patchelf
                          Building wheel for ninja (pyproject.toml): started
                          Building wheel for ninja (pyproject.toml): finished with status 'error'
                          error: subprocess-exited-with-error

                          × Building wheel for ninja (pyproject.toml) did not run successfully.
                          │ exit code: 1
                          ╰─> [15 lines of output]
                              /data/data/com.termux/files/usr/tmp/pip-build-env-38rrenj8/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:312: UserWarning: git archive did not support describe output
                                warnings.warn("git archive did not support describe output")
                              /data/data/com.termux/files/usr/tmp/pip-build-env-38rrenj8/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:331: UserWarning: unprocessed git archival found (no export subst applied)
                                warnings.warn("unprocessed git archival found (no export subst applied)")
                              Traceback (most recent call last):
                                File "/data/data/com.termux/files/usr/tmp/pip-build-env-38rrenj8/overlay/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 639, in setup
                                  cmkr = cmaker.CMaker(cmake_executable)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                File "/data/data/com.termux/files/usr/tmp/pip-build-env-38rrenj8/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 145, in __init__
                                  self.cmake_version = get_cmake_version(self.cmake_executable)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                File "/data/data/com.termux/files/usr/tmp/pip-build-env-38rrenj8/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                                  raise SKBuildError(msg) from err

                              Problem with the CMake installation, aborting build. CMake executable is cmake
                              [end of output]

                          note: This error originates from a subprocess, and is likely not a problem with pip.
                          ERROR: Failed building wheel for ninja
                          Building wheel for patchelf (pyproject.toml): started
                          Building wheel for patchelf (pyproject.toml): finished with status 'error'
                          error: subprocess-exited-with-error

                          × Building wheel for patchelf (pyproject.toml) did not run successfully.
                          │ exit code: 1
                          ╰─> [26 lines of output]
                              /data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py:251: _IncompatibleBdistWheel: wheel.bdist_wheel is deprecated, please import it from setuptools
                              !!

                                      ********************************************************************************
                                      Ensure that any custom bdist_wheel implementation is a subclass of
                                      setuptools.command.bdist_wheel.bdist_wheel.

                                      By 2025-Oct-15, you need to update your project and remove deprecated calls
                                      or your builds will no longer be supported.

                                      See https://github.com/pypa/wheel/pull/631 for details.
                                      ********************************************************************************

                              !!
                                return _build_backend().build_wheel(wheel_directory, config_settings,
                              Traceback (most recent call last):
                                File "/data/data/com.termux/files/usr/tmp/pip-build-env-ahzwci_4/overlay/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 639, in setup
                                  cmkr = cmaker.CMaker(cmake_executable)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                File "/data/data/com.termux/files/usr/tmp/pip-build-env-ahzwci_4/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 145, in __init__
                                  self.cmake_version = get_cmake_version(self.cmake_executable)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                File "/data/data/com.termux/files/usr/tmp/pip-build-env-ahzwci_4/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                                  raise SKBuildError(msg) from err

                              Problem with the CMake installation, aborting build. CMake executable is cmake
                              [end of output]

                          note: This error originates from a subprocess, and is likely not a problem with pip.
                          ERROR: Failed building wheel for patchelf
                        Failed to build ninja patchelf
                        ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ninja, patchelf)
                        [end of output]

                    note: This error originates from a subprocess, and is likely not a problem with pip.
                  error: subprocess-exited-with-error

                  × pip subprocess to install backend dependencies did not run successfully.
                  │ exit code: 1
                  ╰─> See above for output.

                  note: This error originates from a subprocess, and is likely not a problem with pip.
                  [end of output]

              note: This error originates from a subprocess, and is likely not a problem with pip.
            error: subprocess-exited-with-error

            × pip subprocess to install build dependencies did not run successfully.
            │ exit code: 1
            ╰─> See above for output.

            note: This error originates from a subprocess, and is likely not a problem with pip.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × pip subprocess to install build dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by J0nVan** [comment]
Tell me, did you not solve this problem? I have a squeaky tack to install a 19-line module "requirements.txt" – blis.

 The load hangs at this point (photo)  

![Image](https://github.com/user-attachments/assets/5a4edc5e-1f81-4e1b-a7c7-93a9173de2f6)

 Later: 
_pip subprocess to install build dependencies did not run successfully._

**Comment by TermuxHackz** [comment]
Fixed. spacy is now in requirements.txt and setup.sh installs it and downloads the en_core_web_sm model for you automatically (including the --break-system-packages flag spaCy's downloader needs on Kali/Debian/current Termux). Pull the latest master and re-run `bash setup.sh`.
